# Generated by Django 5.2.4 on 2025-10-23 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "serial_number",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("course_name", models.CharField(max_length=150)),
                ("course_link", models.URLField(blank=True, max_length=500, null=True)),
                ("course_duration_hours", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "serial_number",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                (
                    "cnic",
                    models.CharField(
                        help_text="Format: XXXXX-XXXXXXX-X", max_length=15, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("joining_date", models.DateField()),
                ("resignation_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseEnrolment",
            fields=[
                (
                    "serial_number",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("enrolment_date", models.DateField()),
                ("deadline", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Semester 1", "Semester 1"),
                            ("Semester 2", "Semester 2"),
                            ("Semester 3", "Semester 3"),
                            ("Semester 4", "Semester 4"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to="core.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="course_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_headed",
                to="core.student",
            ),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "serial_number",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("Quiz", "Quiz"), ("Practical", "Practical")],
                        max_length=50,
                    ),
                ),
                ("exam_date", models.DateField()),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("obtained_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "course_enrolment",
                    models.ForeignKey(
                        help_text="Links to the specific student-course enrolment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="core.courseenrolment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("obtained_marks__lte", models.F("total_marks"))
                        ),
                        name="obtained_lte_total_marks",
                    )
                ],
            },
        ),
    ]
