# Generated by Django 5.1.4 on 2025-10-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseenrolment",
            name="active_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="active_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
    ]
